// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUdUpKmmvwPVPNwltToSAORqtJMA1WXcU',
    appId: '1:141324390335:web:2f1c625882a95716fb9b0a',
    messagingSenderId: '141324390335',
    projectId: 'my-beats-84f9f',
    authDomain: 'my-beats-84f9f.firebaseapp.com',
    storageBucket: 'my-beats-84f9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWXrem5LQTyqXWxevsNPxm3FwpJFs3CM8',
    appId: '1:141324390335:android:33749f3df2ca8f84fb9b0a',
    messagingSenderId: '141324390335',
    projectId: 'my-beats-84f9f',
    storageBucket: 'my-beats-84f9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyvlO7XeAP2KW4M_9YDCPTeDA90BVHmlQ',
    appId: '1:141324390335:ios:ab138a3ebdfedf5dfb9b0a',
    messagingSenderId: '141324390335',
    projectId: 'my-beats-84f9f',
    storageBucket: 'my-beats-84f9f.appspot.com',
    iosBundleId: 'com.example.myBeats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyvlO7XeAP2KW4M_9YDCPTeDA90BVHmlQ',
    appId: '1:141324390335:ios:0e179cf543a747a3fb9b0a',
    messagingSenderId: '141324390335',
    projectId: 'my-beats-84f9f',
    storageBucket: 'my-beats-84f9f.appspot.com',
    iosBundleId: 'com.example.myBeats.RunnerTests',
  );
}
